apiVersion: v1
kind: Secret
metadata:
  name: cluster-use1-apps-dev-a
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    argocd.argoproj.io/auto-label-cluster-info: "true"
    env: nonprod
    region: us-east-1
    team: team-a
    type: standard
    ready: "true"
  annotations:
    account-id: "111122223333"
type: Opaque
stringData:
  name: use1-apps-dev-a
  server: https://use1-apps-dev-a.eks.us-east-1.amazonaws.com
  config: |
    {
      "awsAuthConfig": {
        "clusterName": "use1-apps-dev-a",
        "roleARN": "arn:aws:iam::111122223333:role/argocd-use1-apps-dev-a"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<base64-encoded-cluster-ca>"
      }
    }
