apiVersion: v1
kind: Secret
metadata:
  name: cluster-use1-hub-prod
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    argocd.argoproj.io/auto-label-cluster-info: "true"
    env: prod
    region: us-east-1
    type: hub
    ready: "true"
  annotations:
    account-id: "111122223333"
type: Opaque
stringData:
  name: use1-hub-prod
  server: https://kubernetes.default.svc
