apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-a-prod
  namespace: argocd
spec:
  description: Team A production workloads
  sourceNamespaces:
    - argocd
  sourceRepos:
    - https://github.com/example-org/team-a-gitops.git
    - https://github.com/example-org/payments-api-deploy.git
    - https://github.com/example-org/checkout-ui-deploy.git
  destinations:
    - server: https://use1-apps-prod-a.eks.us-east-1.amazonaws.com
      namespace: payments
    - server: https://use1-apps-prod-b.eks.us-east-1.amazonaws.com
      namespace: payments
    - server: https://use1-apps-prod-a.eks.us-east-1.amazonaws.com
      namespace: checkout
    - server: https://use1-apps-prod-b.eks.us-east-1.amazonaws.com
      namespace: checkout
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
