apiVersion: v1
kind: Secret
metadata:
  name: cluster-apps-nonprod-a
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    account-id: "111122223333"
  labels:
    argocd.argoproj.io/secret-type: cluster
    argocd.argoproj.io/auto-label-cluster-info: "true"
    env: nonprod
    class: workload
    region: us-east-1
    workload.gha-runners/enabled: "true"
    ready: "true"
type: Opaque
stringData:
  name: apps-nonprod-a
  server: https://apps-nonprod-a.eks.us-east-1.amazonaws.com
  config: |
    {
      "awsAuthConfig": {
        "clusterName": "apps-nonprod-a",
        "roleARN": "arn:aws:iam::111122223333:role/argocd-apps-nonprod-a"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<base64-encoded-cluster-ca>"
      }
    }
