apiVersion: v1
kind: Secret
metadata:
  name: cluster-mgmt-nonprod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    account-id: "111122223333"
  labels:
    argocd.argoproj.io/secret-type: cluster
    argocd.argoproj.io/auto-label-cluster-info: "true"
    env: nonprod
    class: management
    region: us-east-1
    ready: "true"
type: Opaque
stringData:
  name: mgmt-nonprod
  server: https://mgmt-nonprod.eks.us-east-1.amazonaws.com
  config: |
    {
      "awsAuthConfig": {
        "clusterName": "mgmt-nonprod",
        "roleARN": "arn:aws:iam::111122223333:role/argocd-mgmt-nonprod"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<base64-encoded-cluster-ca>"
      }
    }
