configs:
  credentialTemplates:
    github-example-org:
      url: https://github.com/example-org
      githubAppID: 1
      githubAppInstallationID: 2
      githubAppPrivateKey: |
        -----BEGIN RSA PRIVATE KEY-----
        replace-me
        -----END RSA PRIVATE KEY-----
