global:
  domain: argocd.platform.example.com

configs:
  params:
    server.insecure: true
  cm:
    url: https://argocd.platform.example.com
    exec.enabled: false

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: argocd.platform.example.com
    tls: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

notifications:
  enabled: true
